"""The managed environment file a repository's ``setup.sh`` writes and its ``activate.sh`` sources.

Run as ``python -m substrax.runtime.managed_env write --prefix DATARAX --backend auto --output
.datarax.env`` after the project environment is synced. The file declares every variable it
manages in ``<PREFIX>_MANAGED_ENV_VARS``, so ``activate.sh`` can unset them before sourcing a new
one, then exports or unsets each. The JAX settings come from :class:`JaxRuntime` through
:func:`runtime_environment`, so the file uses the names jax reads today: the memory fraction is
``XLA_CLIENT_MEM_FRACTION``, and the deprecated ``XLA_PYTHON_CLIENT_MEM_FRACTION``, which jaxlib
refuses beside it, is always unset. Preallocation and the memory fraction apply only to an
accelerator backend: jaxlib reads them when it builds the GPU plugin's options, so on the CPU they
are unset. A repository adds its own variables (for example TensorFlow's log level) with ``--set``.

Importing this module imports no jax.
"""

from __future__ import annotations

import argparse
import platform
import re
import shlex
import shutil
import subprocess  # nosec B404 - runs only nvidia-smi, resolved to an absolute path
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path

from substrax.runtime.config import JaxRuntime
from substrax.runtime.environment import runtime_environment


BACKENDS = ("auto", "cpu", "cuda12", "metal")
ACCELERATOR_BACKENDS = ("cuda12", "metal")
ACCELERATOR_MEMORY_FRACTION = 0.75
# Every JAX variable the file manages, whether a backend sets it or not, so a stale value from an
# earlier file or the shell is cleared.
JAX_VARIABLES = (
    "JAX_ENABLE_X64",
    "JAX_PLATFORMS",
    "XLA_PYTHON_CLIENT_PREALLOCATE",
    "XLA_CLIENT_MEM_FRACTION",
    "XLA_PYTHON_CLIENT_MEM_FRACTION",
)
_PREFIX = re.compile(r"[A-Z][A-Z0-9_]*")


def nvidia_gpu_visible() -> bool:
    """Whether ``nvidia-smi`` lists at least one GPU."""
    nvidia_smi = shutil.which("nvidia-smi")
    if nvidia_smi is None:
        return False
    try:
        result = subprocess.run(  # noqa: S603  # nosec B603 - absolute path from shutil.which
            [nvidia_smi, "-L"], check=False, capture_output=True, text=True, timeout=5
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return result.returncode == 0 and bool(result.stdout.strip())


def resolve_backend(requested: str) -> str:
    """The concrete backend for ``requested``, resolving ``auto`` from the host."""
    if requested != "auto":
        return requested
    if platform.system() == "Linux" and nvidia_gpu_visible():
        return "cuda12"
    if platform.system() == "Darwin" and platform.machine().lower() == "arm64":
        return "metal"
    return "cpu"


def managed_environment(
    *, prefix: str, backend: str, project_root: Path, extra: Mapping[str, str]
) -> dict[str, str | None]:
    """Every managed variable mapped to its value, or ``None`` for a variable the file unsets.

    Args:
        prefix: The repository's variable prefix, such as ``"DATARAX"``.
        backend: One of :data:`BACKENDS`; ``auto`` is resolved first.
        project_root: The repository root, written as ``<PREFIX>_ENV_ROOT``.
        extra: The repository's own variables, written as given.

    Returns:
        The managed variables in the order they are written.

    Raises:
        ValueError: If the prefix is not an upper-case shell name, the backend is unknown, or
            ``extra`` names a variable the file manages itself.
    """
    if not _PREFIX.fullmatch(prefix):
        raise ValueError(f"prefix {prefix!r} must be an upper-case shell name, such as 'DATARAX'")
    if backend not in BACKENDS:
        raise ValueError(f"backend {backend!r} is not one of {', '.join(BACKENDS)}")
    resolved = resolve_backend(backend)
    owned = (f"{prefix}_BACKEND", f"{prefix}_ENV_ROOT", *JAX_VARIABLES)
    if clash := sorted(set(extra) & set(owned)):
        raise ValueError(f"extra variables {clash} are managed by substrax and cannot be set")
    accelerator = resolved in ACCELERATOR_BACKENDS
    runtime = JaxRuntime(
        platforms=None if accelerator else ("cpu",),
        enable_x64=False,
        preallocate=False if accelerator else None,
        memory_fraction=ACCELERATOR_MEMORY_FRACTION if accelerator else None,
    )
    jax_values: dict[str, str | None] = dict.fromkeys(JAX_VARIABLES)
    jax_values.update(runtime_environment(runtime, {}))
    return {
        f"{prefix}_BACKEND": resolved,
        f"{prefix}_ENV_ROOT": str(project_root),
        **jax_values,
        **extra,
    }


def render(*, prefix: str, values: Mapping[str, str | None]) -> str:
    """The shell text of a managed environment file: the manifest, then one line per variable."""
    lines = [
        "# Generated by `python -m substrax.runtime.managed_env`; regenerate it instead of editing.",
        f"export {prefix}_MANAGED_ENV_VARS={shlex.quote(' '.join(values))}",
    ]
    lines += [
        f"unset {name}" if value is None else f"export {name}={shlex.quote(value)}"
        for name, value in values.items()
    ]
    return "\n".join(lines) + "\n"


def _configured_backend(env_file: Path, prefix: str) -> str:
    marker = f"export {prefix}_BACKEND="
    for line in env_file.read_text().splitlines():
        if line.startswith(marker):
            return shlex.split(line.removeprefix("export "))[0].split("=", 1)[1]
    return "unknown"


def _assignment(text: str) -> tuple[str, str]:
    name, separator, value = text.partition("=")
    if not separator or not name:
        raise argparse.ArgumentTypeError(f"--set expects NAME=VALUE, got {text!r}")
    return name, value


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m substrax.runtime.managed_env", description=__doc__
    )
    commands = parser.add_subparsers(dest="command", required=True)
    write = commands.add_parser("write", help="write the managed environment file")
    show = commands.add_parser("show", help="report the managed and user environment layers")
    for command in (write, show):
        command.add_argument("--prefix", required=True, help="the repository's variable prefix")
        command.add_argument("--project-root", type=Path, default=Path.cwd())
    write.add_argument("--backend", choices=BACKENDS, default="auto")
    write.add_argument("--output", type=Path, required=True)
    write.add_argument(
        "--set",
        dest="extra",
        action="append",
        type=_assignment,
        default=[],
        metavar="NAME=VALUE",
        help="a repository variable to write; repeatable",
    )
    show.add_argument("--env-file", type=Path, required=True)
    show.add_argument(
        "--user-env",
        action="append",
        default=[],
        metavar="FILE",
        help="a user-owned layer sourced after the managed file, relative to the project root",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run the ``write`` or ``show`` command.

    Args:
        argv: The arguments after the module name; the process arguments when ``None``.

    Returns:
        The exit status.
    """
    args = _parser().parse_args(argv)
    if args.command == "write":
        values = managed_environment(
            prefix=args.prefix,
            backend=args.backend,
            project_root=args.project_root.resolve(),
            extra=dict(args.extra),
        )
        args.output.write_text(render(prefix=args.prefix, values=values))
        sys.stdout.write(f"Wrote {args.output} for backend '{values[f'{args.prefix}_BACKEND']}'.\n")
        return 0
    root = args.project_root
    lines = [f"Project root: {root}", f".venv present: {(root / '.venv').exists()}"]
    lines.append(f"{args.env_file.name} present: {args.env_file.exists()}")
    lines += [f"{name} present: {(root / name).exists()}" for name in args.user_env]
    backend = _configured_backend(args.env_file, args.prefix) if args.env_file.exists() else "none"
    lines.append(f"Configured backend: {backend}")
    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
