#!/usr/bin/env python3
"""Write and inspect the generated Substrax environment file used by activate.sh."""

from __future__ import annotations

import argparse
import platform
import shlex
import shutil
import subprocess
import sys
from pathlib import Path


SUPPORTED_BACKENDS = {"auto", "cpu", "cuda12", "metal"}
MANAGED_ENV_VARS = (
    "SUBSTRAX_BACKEND",
    "SUBSTRAX_ENV_ROOT",
    "JAX_ENABLE_X64",
    "JAX_PLATFORMS",
    "TF_CPP_MIN_LOG_LEVEL",
    "XLA_PYTHON_CLIENT_MEM_FRACTION",
    "XLA_PYTHON_CLIENT_PREALLOCATE",
    "PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION",
)


def emit(message: str) -> None:
    """Write a single line to stdout."""
    sys.stdout.write(f"{message}\n")


def detect_linux_nvidia_gpu() -> bool:
    """Return True when `nvidia-smi` reports at least one visible NVIDIA GPU."""
    nvidia_smi = shutil.which("nvidia-smi")
    if nvidia_smi is None:
        return False
    try:
        # The executable is the absolute path shutil.which resolved; no user input reaches it.
        result = subprocess.run(  # noqa: S603
            [nvidia_smi, "-L"],
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (FileNotFoundError, subprocess.SubprocessError):
        return False

    return result.returncode == 0 and bool(result.stdout.strip())


def resolve_backend(requested_backend: str) -> str:
    """Resolve `auto` to a concrete backend choice for the current host."""
    if requested_backend != "auto":
        return requested_backend

    system = platform.system()
    machine = platform.machine().lower()
    if system == "Linux" and detect_linux_nvidia_gpu():
        return "cuda12"
    if system == "Darwin" and machine == "arm64":
        return "metal"
    return "cpu"


def build_env_contents(project_root: Path, backend: str) -> str:
    """Build the generated managed environment file contents."""
    managed_values = {
        "SUBSTRAX_BACKEND": backend,
        "SUBSTRAX_ENV_ROOT": str(project_root),
        "JAX_ENABLE_X64": "0",
        "JAX_PLATFORMS": "cpu" if backend == "cpu" else None,
        "TF_CPP_MIN_LOG_LEVEL": "1",
        "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.75",
        "XLA_PYTHON_CLIENT_PREALLOCATE": "false",
        "PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION": "python",
    }

    lines = [
        "# Generated by scripts/setup_env.py.",
        "# JAX selects the best available backend by default.",
        f"export SUBSTRAX_MANAGED_ENV_VARS={shlex.quote(' '.join(MANAGED_ENV_VARS))}",
    ]

    for variable in MANAGED_ENV_VARS:
        value = managed_values[variable]
        if value is None:
            lines.append(f"unset {variable}")
        else:
            lines.append(f"export {variable}={shlex.quote(value)}")

    return "\n".join(lines) + "\n"


def write_env_file(project_root: Path, backend: str, output_path: Path) -> None:
    """Write the generated managed environment file for the requested backend."""
    resolved_backend = resolve_backend(backend)
    output_path.write_text(build_env_contents(project_root, resolved_backend))
    emit(f"Wrote {output_path} for backend '{resolved_backend}'.")


def show_status(project_root: Path, env_path: Path) -> int:
    """Print the current setup status."""
    emit(f"Project root: {project_root}")
    emit(f".venv present: {(project_root / '.venv').exists()}")
    emit(f"{env_path.name} present: {env_path.exists()}")
    emit(f".env present: {(project_root / '.env').exists()}")
    emit(f".env.local present: {(project_root / '.env.local').exists()}")
    if env_path.exists():
        backend = next(
            (
                line.split("=", 1)[1].strip().strip('"')
                for line in env_path.read_text().splitlines()
                if line.startswith("export SUBSTRAX_BACKEND=")
            ),
            "unknown",
        )
        emit(f"Configured backend: {backend}")
    else:
        emit("Configured backend: none")
    return 0


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    write_parser = subparsers.add_parser("write", help="Write the generated Substrax env file")
    write_parser.add_argument(
        "--backend",
        choices=sorted(SUPPORTED_BACKENDS),
        default="auto",
        help="Backend policy to encode in the environment file",
    )
    write_parser.add_argument(
        "--output",
        default=".substrax.env",
        help="Path to the generated environment file to write",
    )

    show_parser = subparsers.add_parser("show", help="Show generated/user env layering status")
    show_parser.add_argument(
        "--env-file",
        default=".substrax.env",
        help="Managed env file to inspect",
    )

    return parser.parse_args()


def main() -> int:
    """Run the requested subcommand."""
    args = parse_args()
    project_root = Path.cwd()

    if args.command == "write":
        write_env_file(project_root, args.backend, Path(args.output))
        return 0

    if args.command == "show":
        return show_status(project_root, Path(args.env_file))

    raise RuntimeError(f"unsupported command: {args.command}")


if __name__ == "__main__":
    sys.exit(main())
